server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: getway
          uri: https://github.com/salvadorEstrada/practice-microservice
          search-paths: config-data
  application:
    name: config-service

